version: '3'

services:
  web:
    image: registry.realt.community/stats-realt:${DOCKER_BRANCH}
    container_name: ${DOCKER_BRANCH}-stats
    ports:
      - "8082:80"
    networks:
      - traefik-realt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stats-preprod.rule=Host(`stats.preprod.realt.community`)"
      - "traefik.http.routers.stats-preprod.entrypoints=websecure"
    restart: always

networks:
  traefik-realt:
    external: true
