name: Build docker image

on:
  push:
    branches:
      - preprod

jobs:
  build:
    name: Docker build & Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3       

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          
      - name: List files
        run: ls -al