name: Build docker image

on:
  push:
    branches:
      - preprod

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
       - name: Connect to remote server
         uses: appleboy/ssh-action@master
         with:
          host: ${{ secrets.KURTISONELAB_SSH_HOST }}
          username: ${{ secrets.KURTISONELAB_SSH_USER }}
          password: ${{ secrets.KURTISONELAB_SSH_PASSWORD }}
          port: ${{ secrets.KURTISONELAB_SSH_PORT }}
          # passphrase: ${{ secrets.KURTISONELAB_SSH_KNOWN_HOST }}
          script: |
            cd ./RealT-Stats
            git pull
            docker build -t realtoken-community/realtoken-stat