name: Build docker image

on:
  workflow_dispatch:
  
  push:
    branches:
      - dev

jobs:
  build:
    name: Docker build & Artifact
    runs-on: ubuntu-latest
    steps:

       - name: ssh key passphrase
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KURTISONELAB_SSH_HOST }}
          username: ${{ secrets.KURTISONELAB_SSH_USER }}
          key: ${{ secrets.KURTISONELAB_SSH_KEY }}
          port: ${{ secrets.KURTISONELAB_SSH_PORT }}
          # passphrase: ${{ secrets.KURTISONELAB_SSH_KNOWN_HOST }}
          script: ls -al