name: To registry, pull and up

on:
  push:
    branches:
      - preprod

jobs:
  build:
    name: Build, push, pull & up
    runs-on: ubuntu-latest
    steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: https://registry.realt.community:5000/realtokencommunity/realtstats_preprod