name: To registry

on:
  push:
    branches:
      - preprod

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: kurtisone.duckdns.org/realtoken-community/realtoken-stat