name: Deploy server over CI/CD

on: workflow_dispatch

permissions:
    contents: read

jobs:
  build:
    name: Build, push, pull & up
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Replace API Key
          env:
            API: ${{ secrets.API_KEY }}
          run: sed -i -e "s/secret.API_KEY/$API/" assets/js/main.js

        -   name: Login to registry
            uses: docker/login-action@v3
            with:
                registry: ${{ secrets.DOCKER_REGISTRY }}
                username: ${{ secrets.DOCKER_LOGIN }}
                password: ${{ secrets.DOCKER_PASSWD }}

        -   name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
                context: .
                push: true
                tags: ${{ secrets.DOCKER_REGISTRY }}/stats-test-realt:${{ github.ref_name }}
                      
